plugins {
    id 'java'
}

group 'ru.netology'
version '1.0-SNAPSHOT'

java {
    sourceCompatibility = 11
}

compileJava.options.encoding = "UTF-8"
compileTestJava.options.encoding = "UTF-8"

repositories {
    mavenCentral()
}

dependencies {

    testImplementation 'org.junit.jupiter:junit-jupiter:5.9.2'
    testImplementation 'com.codeborne:selenide:6.15.0'
    testImplementation 'org.slf4j:slf4j-simple:2.0.7'

    dependencies {
        testImplementation 'org.junit.jupiter:junit-jupiter:5.9.2'
        testImplementation 'com.codeborne:selenide:6.15.0'
        testImplementation 'org.slf4j:slf4j-simple:2.0.7'
        compileOnly 'org.projectlombok:lombok:1.18.30'
        annotationProcessor 'org.projectlombok:lombok:1.18.30'
        testCompileOnly 'org.projectlombok:lombok:1.18.30'
        testAnnotationProcessor 'org.projectlombok:lombok:1.18.30'
    }

    testImplementation 'org.junit.jupiter:junit-jupiter:5.10.2'
    testImplementation 'com.codeborne:selenide:6.19.1'

}

test {
    useJUnitPlatform()

    systemProperty 'selenide.headless', System.getProperty('selenide.headless', 'false')
    systemProperty 'selenide.browser', System.getProperty('selenide.browser', 'chrome')
    systemProperty 'selenide.timeout', '10000'

    systemProperty 'selenide.headless', System.getProperty('selenide.headless')
    systemProperty 'chromeoptions.prefs', System.getProperty('chromeoptions.prefs', "profile.password_manager_leak_detection=false")

}